(define (problem menu-semanal-extension-e5)
	(:domain menu_semanal)
	(:objects
		lun mar mie jue vie - dia
		carne sopa arroz crema ensalada pescado - tipo_plato
		sopa_de_pollo sopa_minestrone sopa_de_tomate sopa_de_lentejas ensalada_de_atun ensalada_de_quinoa crema_de_esparragos crema_de_calabaza - primero
		filete_de_ternera pollo_asado costillas_a_la_barbacoa merluza_en_salsa_verde salmon_a_la_plancha calamares_a_la_romana arroz_al_horno arroz_a_la_cubana paella_mixta arroz_con_costra arroz_meloso_de_verduras - segundo
	)

	(:init
		(es_tipo sopa_de_pollo sopa)
		(= (calorias sopa_de_pollo) 285)
		(= (precio sopa_de_pollo) 4.5)
		(es_tipo sopa_minestrone sopa)
		(= (calorias sopa_minestrone) 304)
		(= (precio sopa_minestrone) 4.2)
		(es_tipo sopa_de_tomate sopa)
		(= (calorias sopa_de_tomate) 266)
		(= (precio sopa_de_tomate) 3.9)
		(es_tipo sopa_de_lentejas sopa)
		(= (calorias sopa_de_lentejas) 342)
		(= (precio sopa_de_lentejas) 4.0)
		(es_tipo ensalada_de_atun ensalada)
		(= (calorias ensalada_de_atun) 361)
		(= (precio ensalada_de_atun) 5.8)
		(es_tipo ensalada_de_quinoa ensalada)
		(= (calorias ensalada_de_quinoa) 323)
		(= (precio ensalada_de_quinoa) 5.5)
		(es_tipo crema_de_esparragos crema)
		(= (calorias crema_de_esparragos) 247)
		(= (precio crema_de_esparragos) 4.4)
		(es_tipo crema_de_calabaza crema)
		(= (calorias crema_de_calabaza) 304)
		(= (precio crema_de_calabaza) 4.9)

		(es_tipo filete_de_ternera carne)
		(= (calorias filete_de_ternera) 1140)
		(= (precio filete_de_ternera) 12.0)
		(es_tipo pollo_asado carne)
		(= (calorias pollo_asado) 1045)
		(= (precio pollo_asado) 11.5)
		(es_tipo costillas_a_la_barbacoa carne)
		(= (calorias costillas_a_la_barbacoa) 1330)
		(= (precio costillas_a_la_barbacoa) 14.0)
		(es_tipo merluza_en_salsa_verde pescado)
		(= (calorias merluza_en_salsa_verde) 912)
		(= (precio merluza_en_salsa_verde) 12.0)
		(es_tipo salmon_a_la_plancha pescado)
		(= (calorias salmon_a_la_plancha) 988)
		(= (precio salmon_a_la_plancha) 13.5)
		(es_tipo calamares_a_la_romana pescado)
		(= (calorias calamares_a_la_romana) 1140)
		(= (precio calamares_a_la_romana) 12.8)
		(es_tipo arroz_al_horno arroz)
		(= (calorias arroz_al_horno) 1140)
		(= (precio arroz_al_horno) 13.0)
		(es_tipo arroz_a_la_cubana arroz)
		(= (calorias arroz_a_la_cubana) 1216)
		(= (precio arroz_a_la_cubana) 12.8)
		(es_tipo paella_mixta arroz)
		(= (calorias paella_mixta) 1235)
		(= (precio paella_mixta) 14.0)
		(es_tipo arroz_con_costra arroz)
		(= (calorias arroz_con_costra) 1178)
		(= (precio arroz_con_costra) 13.5)
		(es_tipo arroz_meloso_de_verduras arroz)
		(= (calorias arroz_meloso_de_verduras) 1102)
		(= (precio arroz_meloso_de_verduras) 12.0)

		(incompatible sopa_de_pollo costillas_a_la_barbacoa)
		(incompatible sopa_de_lentejas filete_de_ternera)
		(incompatible sopa_minestrone calamares_a_la_romana)
		(incompatible crema_de_calabaza paella_mixta)
		(incompatible crema_de_esparragos arroz_a_la_cubana)
		(incompatible sopa_de_lentejas costillas_a_la_barbacoa)

		(obligatorio_dia merluza_en_salsa_verde lun)
		(obligatorio_dia ensalada_de_quinoa vie)
		(obligatorio_dia arroz_al_horno mar)

		(dia_siguiente lun mar)
		(dia_siguiente mar mie)
		(dia_siguiente mie jue)
		(dia_siguiente jue vie)

		(= (precio_total) 0)
		(= (calorias_dia lun) 0)
		(= (calorias_dia mar) 0)
		(= (calorias_dia mie) 0)
		(= (calorias_dia jue) 0)
		(= (calorias_dia vie) 0)
	)

	(:goal 
		(and
			(dia_completo lun)
			(dia_completo mar)
			(dia_completo mie)
			(dia_completo jue)
			(dia_completo vie)
		)
	)
	(:metric minimize (precio_total))
)
