(define (problem menu-semanal-extension-e5)
	(:domain menu_semanal)
	(:objects
		lun mar mie jue vie - dia
		ensalada pescado crema sopa carne arroz - tipo_plato
		sopa_de_verduras sopa_de_lentejas sopa_minestrone sopa_de_pollo sopa_de_tomate ensalada_caprese ensalada_de_atun ensalada_griega ensalada_de_quinoa ensalada_cesar crema_de_calabaza crema_de_esparragos crema_de_zanahoria crema_de_aguacate - primero
		filete_de_ternera albondigas atun_a_la_parrilla merluza_en_salsa_verde salmon_a_la_plancha bacalao_al_horno paella_mixta arroz_a_la_cubana arroz_meloso_de_verduras arroz_con_costra - segundo
	)

	(:init
		(es_tipo sopa_de_verduras sopa)
		(= (calorias sopa_de_verduras) 228)
		(= (precio sopa_de_verduras) 3.8)
		(es_tipo sopa_de_lentejas sopa)
		(= (calorias sopa_de_lentejas) 342)
		(= (precio sopa_de_lentejas) 4.0)
		(es_tipo sopa_minestrone sopa)
		(= (calorias sopa_minestrone) 304)
		(= (precio sopa_minestrone) 4.2)
		(es_tipo sopa_de_pollo sopa)
		(= (calorias sopa_de_pollo) 285)
		(= (precio sopa_de_pollo) 4.5)
		(es_tipo sopa_de_tomate sopa)
		(= (calorias sopa_de_tomate) 266)
		(= (precio sopa_de_tomate) 3.9)
		(es_tipo ensalada_caprese ensalada)
		(= (calorias ensalada_caprese) 285)
		(= (precio ensalada_caprese) 5.3)
		(es_tipo ensalada_de_atun ensalada)
		(= (calorias ensalada_de_atun) 361)
		(= (precio ensalada_de_atun) 5.8)
		(es_tipo ensalada_griega ensalada)
		(= (calorias ensalada_griega) 209)
		(= (precio ensalada_griega) 4.7)
		(es_tipo ensalada_de_quinoa ensalada)
		(= (calorias ensalada_de_quinoa) 323)
		(= (precio ensalada_de_quinoa) 5.5)
		(es_tipo ensalada_cesar ensalada)
		(= (calorias ensalada_cesar) 247)
		(= (precio ensalada_cesar) 5.0)
		(es_tipo crema_de_calabaza crema)
		(= (calorias crema_de_calabaza) 304)
		(= (precio crema_de_calabaza) 4.9)
		(es_tipo crema_de_esparragos crema)
		(= (calorias crema_de_esparragos) 247)
		(= (precio crema_de_esparragos) 4.4)
		(es_tipo crema_de_zanahoria crema)
		(= (calorias crema_de_zanahoria) 228)
		(= (precio crema_de_zanahoria) 4.2)
		(es_tipo crema_de_aguacate crema)
		(= (calorias crema_de_aguacate) 342)
		(= (precio crema_de_aguacate) 5.0)

		(es_tipo filete_de_ternera carne)
		(= (calorias filete_de_ternera) 1140)
		(= (precio filete_de_ternera) 12.0)
		(es_tipo albondigas carne)
		(= (calorias albondigas) 1102)
		(= (precio albondigas) 11.0)
		(es_tipo atun_a_la_parrilla pescado)
		(= (calorias atun_a_la_parrilla) 1007)
		(= (precio atun_a_la_parrilla) 13.2)
		(es_tipo merluza_en_salsa_verde pescado)
		(= (calorias merluza_en_salsa_verde) 912)
		(= (precio merluza_en_salsa_verde) 12.0)
		(es_tipo salmon_a_la_plancha pescado)
		(= (calorias salmon_a_la_plancha) 988)
		(= (precio salmon_a_la_plancha) 13.5)
		(es_tipo bacalao_al_horno pescado)
		(= (calorias bacalao_al_horno) 950)
		(= (precio bacalao_al_horno) 12.5)
		(es_tipo paella_mixta arroz)
		(= (calorias paella_mixta) 1235)
		(= (precio paella_mixta) 14.0)
		(es_tipo arroz_a_la_cubana arroz)
		(= (calorias arroz_a_la_cubana) 1216)
		(= (precio arroz_a_la_cubana) 12.8)
		(es_tipo arroz_meloso_de_verduras arroz)
		(= (calorias arroz_meloso_de_verduras) 1102)
		(= (precio arroz_meloso_de_verduras) 12.0)
		(es_tipo arroz_con_costra arroz)
		(= (calorias arroz_con_costra) 1178)
		(= (precio arroz_con_costra) 13.5)

		(incompatible sopa_de_lentejas filete_de_ternera)
		(incompatible sopa_de_tomate atun_a_la_parrilla)
		(incompatible ensalada_griega merluza_en_salsa_verde)
		(incompatible ensalada_de_quinoa bacalao_al_horno)
		(incompatible ensalada_de_atun atun_a_la_parrilla)
		(incompatible crema_de_calabaza paella_mixta)
		(incompatible crema_de_esparragos arroz_a_la_cubana)
		(incompatible crema_de_zanahoria arroz_meloso_de_verduras)
		(incompatible crema_de_aguacate albondigas)

		(obligatorio_dia crema_de_zanahoria jue)
		(obligatorio_dia crema_de_esparragos mar)
		(obligatorio_dia ensalada_griega mie)

		(dia_siguiente lun mar)
		(dia_siguiente mar mie)
		(dia_siguiente mie jue)
		(dia_siguiente jue vie)

		(= (precio_total) 0)
		(= (calorias_dia lun) 0)
		(= (calorias_dia mar) 0)
		(= (calorias_dia mie) 0)
		(= (calorias_dia jue) 0)
		(= (calorias_dia vie) 0)
	)

	(:goal 
		(and
			(dia_completo lun)
			(dia_completo mar)
			(dia_completo mie)
			(dia_completo jue)
			(dia_completo vie)
		)
	)
	(:metric minimize (precio_total))
)
