(define (problem menu-semanal-extension-e4)
	(:domain menu_semanal)
	(:objects
		lun mar mie jue vie - dia
		sopa ensalada crema arroz pescado carne - tipo_plato
		sopa_de_lentejas sopa_de_pollo sopa_de_verduras sopa_de_tomate ensalada_griega ensalada_de_quinoa ensalada_caprese crema_de_esparragos crema_de_champinones crema_de_zanahoria crema_de_aguacate - primero
		albondigas pollo_asado filete_de_ternera costillas_a_la_barbacoa bacalao_al_horno salmon_a_la_plancha merluza_en_salsa_verde calamares_a_la_romana atun_a_la_parrilla arroz_a_la_cubana paella_mixta - segundo
	)

	(:init
		(es_tipo sopa_de_lentejas sopa)
		(= (calorias sopa_de_lentejas) 342)
		(es_tipo sopa_de_pollo sopa)
		(= (calorias sopa_de_pollo) 285)
		(es_tipo sopa_de_verduras sopa)
		(= (calorias sopa_de_verduras) 228)
		(es_tipo sopa_de_tomate sopa)
		(= (calorias sopa_de_tomate) 266)
		(es_tipo ensalada_griega ensalada)
		(= (calorias ensalada_griega) 209)
		(es_tipo ensalada_de_quinoa ensalada)
		(= (calorias ensalada_de_quinoa) 323)
		(es_tipo ensalada_caprese ensalada)
		(= (calorias ensalada_caprese) 285)
		(es_tipo crema_de_esparragos crema)
		(= (calorias crema_de_esparragos) 247)
		(es_tipo crema_de_champinones crema)
		(= (calorias crema_de_champinones) 266)
		(es_tipo crema_de_zanahoria crema)
		(= (calorias crema_de_zanahoria) 228)
		(es_tipo crema_de_aguacate crema)
		(= (calorias crema_de_aguacate) 342)

		(es_tipo albondigas carne)
		(= (calorias albondigas) 1102)
		(es_tipo pollo_asado carne)
		(= (calorias pollo_asado) 1045)
		(es_tipo filete_de_ternera carne)
		(= (calorias filete_de_ternera) 1140)
		(es_tipo costillas_a_la_barbacoa carne)
		(= (calorias costillas_a_la_barbacoa) 1330)
		(es_tipo bacalao_al_horno pescado)
		(= (calorias bacalao_al_horno) 950)
		(es_tipo salmon_a_la_plancha pescado)
		(= (calorias salmon_a_la_plancha) 988)
		(es_tipo merluza_en_salsa_verde pescado)
		(= (calorias merluza_en_salsa_verde) 912)
		(es_tipo calamares_a_la_romana pescado)
		(= (calorias calamares_a_la_romana) 1140)
		(es_tipo atun_a_la_parrilla pescado)
		(= (calorias atun_a_la_parrilla) 1007)
		(es_tipo arroz_a_la_cubana arroz)
		(= (calorias arroz_a_la_cubana) 1216)
		(es_tipo paella_mixta arroz)
		(= (calorias paella_mixta) 1235)

		(incompatible sopa_de_pollo costillas_a_la_barbacoa)
		(incompatible sopa_de_lentejas filete_de_ternera)
		(incompatible sopa_de_tomate atun_a_la_parrilla)
		(incompatible ensalada_griega merluza_en_salsa_verde)
		(incompatible ensalada_de_quinoa bacalao_al_horno)
		(incompatible crema_de_esparragos arroz_a_la_cubana)
		(incompatible crema_de_aguacate albondigas)
		(incompatible sopa_de_lentejas costillas_a_la_barbacoa)

		(obligatorio_dia ensalada_de_quinoa mie)
		(obligatorio_dia sopa_de_tomate jue)
		(obligatorio_dia pollo_asado lun)

		(dia_siguiente lun mar)
		(dia_siguiente mar mie)
		(dia_siguiente mie jue)
		(dia_siguiente jue vie)
		(= (calorias_dia lun) 0)
		(= (calorias_dia mar) 0)
		(= (calorias_dia mie) 0)
		(= (calorias_dia jue) 0)
		(= (calorias_dia vie) 0)
	)

	(:goal 
		(and
			(dia_completo lun)
			(dia_completo mar)
			(dia_completo mie)
			(dia_completo jue)
			(dia_completo vie)
		)
	)
)
